name: reto_manantial
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  #utils
  formz: ^0.8.0
  flutter_slidable: ^4.0.0
  uuid: ^4.5.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  lottie: ^3.3.1

  #Arquitectura
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  injectable: ^2.5.0
  get_it: ^8.0.3
  freezed: ^3.1.0
  json_annotation: ^4.9.0

  #firebase
  firebase_auth: ^5.6.2
  firebase_core: ^3.15.1
  
  #storage
  shared_preferences: ^2.5.3

  #Google
  google_sign_in: ^7.1.0

  #maps
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  flutter_map: ^8.1.1
  latlong2: ^0.9.1

  #Llamadas
  url_launcher: ^6.3.1

  #API
  dio: ^5.8.0

  #internet
  connectivity_plus: ^6.1.4

  #Notificaciones
  flutter_local_notifications: ^19.3.0

  #UI
  shimmer: ^3.0.0
  intl: ^0.18.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.5.4
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5
  freezed_annotation: ^3.1.0

flutter:

  uses-material-design: true
  
  assets:
    - assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
